### PR TITLE
feat: make nonce handling configurable

### LINKED ISSUE #102: nonce is optional in callback
In releases before 1.3, the nonce appearing in the id_token was optional and if present was required to be equal to the nonce in the session['omniauth.nonce'] value.  That changed in the 1.3 release where the nonce is now required in the id_token and is an error when missing.

My reading of the apple developer docs is that the nonce is an optional feature and may not appear in the id_token. Their wording makes it sounds like the nonce might be useful for locating a user session if the session cookie wasn't received for some reason (like maybe with non-lax cookies and their POST from a different origin).

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple

```
nonce
A string for associating a client session with the identity token. This value mitigates replay attacks and is present only if you pass it in the authorization request.

nonce_supported
A Boolean value that indicates whether the transaction is on a nonce-supported platform. If you send a nonce in the authorization request, but don’t see the nonce claim in the identity token, check this claim to determine how to proceed. If this claim returns true, treat nonce as mandatory and fail the transaction; otherwise, you can proceed treating the nonce as optional.
```

The nonce can be made to be optional and still enforce the expected value by simply not first requiring that the id_token[:nonce] value exists.

```diff
diff --git a/lib/omniauth/strategies/apple.rb b/lib/omniauth/strategies/apple.rb
index 5ad3a40..faf8e0e 100644
--- a/lib/omniauth/strategies/apple.rb
+++ b/lib/omniauth/strategies/apple.rb
@@ -125,7 +125,7 @@ module OmniAuth
       end

       def verify_nonce!(id_token)
-        invalid_claim! :nonce unless id_token[:nonce] && id_token[:nonce] == stored_nonce
+        invalid_claim! :nonce unless id_token[:nonce] == stored_nonce
       end

       def invalid_claim!(claim)
```

I have a spec test for this path coded up but it doesn't fit very nicely into the current test descriptions and contexts as most of those all force a nonce to be present.  But here is a spec test that fails without the patch above and passes with it.

```diff
diff --git a/spec/omniauth/strategies/apple_spec.rb b/spec/omniauth/strategies/apple_spec.rb
index 2709d1b..10e56ec 100644
--- a/spec/omniauth/strategies/apple_spec.rb
+++ b/spec/omniauth/strategies/apple_spec.rb
@@ -79,6 +79,16 @@ describe OmniAuth::Strategies::Apple do
     WebMock.reset!
   end

+  it 'allows optional nonce' do
+    subject.authorize_params # initializes env, session (for test_mode) and populates 'nonce', 'state'
+    subject.session.delete('omniauth.nonce')  # if no nonce in session => nonce in id_token must also be missing
+    request.params.merge!('id_token' => id_token)
+    expect(valid_id_token_payload).not_to have_key(:nonce)
+    expect { subject.info }.not_to raise_error
+    expect(subject.extra.dig(:raw_info, :id_info, 'nonce_supported')).to eq true
+    expect(subject.extra.dig(:raw_info, :id_info, 'nonce')).to be nil
+  end
+
   describe '#client_options' do
     it 'has correct site' do
       expect(subject.client.site).to eq('https://appleid.apple.com')
```

### LINKED ISSUE #103: Getting error as id_token_claims_invalid | nonce invalid
Hi,

I tried to set up the apple login and signup using omni-auth apple gem in my application. 

**# config/initializers/omniauth.rb:**

I want to get the id_token from the response because I need the user email every time while hitting this URL

```
  provider :apple, Rails.application.credentials[:apple_client_id] // ID from service's bundler (eg: com.domain.api), '',
             authorized_client_ids: [Rails.application.credentials[:apple_ui_client_id]] // ID from app's identifier (eg: com.domain.app),
             scope: 'email name',
             team_id: Rails.application.credentials[:apple_team_id],
             key_id: Rails.application.credentials[:apple_key_id],
             pem: Rails.application.credentials[:apple_private_key] // add the pem content with an extra newline at the end,
             provider_ignores_state: true
```

**Error returns:**

Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, id_token_claims_invalid | nonce invalid          
         
Please help me to sort out this error.

### PR DESCRIPTION
**Pull request by bvogel**
This PR will introduce a individual handling of the nonce validation that is significantly hindered by Apple with using a POST callback.

Added specs, README too.

fixes #102 and 
fixes #103

### CODE REVIEW

**Comment by bvogel** [comment]
@nhosoya bump

**Comment by bvogel** [comment]
@nhosoya bump again

**Comment by bvogel** [comment]
@nhosoya bump again

**Comment by bvogel** [comment]
@nhosoya and another bump. Can we please either merge this or get some kind of reaction?

**Comment by nov** [comment]
don't ignore nonce. at least as a library.

**Comment by bvogel** [comment]
WHAT!!! This PR exactly enables that nonce won't be ignored, it makes it even possible to use it securely! Please reconsider closing this.

To rephrase: without this PR you either have to make your session insecure or you just can't use this gem. With this PR you at least have a choice between a secure and a stupid option (I may rephrase the README even more, so it's clear that using `ignore` isn't a sane option) but using a session open to CSFR is even worse.

**Comment by bvogel** [comment]
@nov @nhosoya Another fun fact, if you check almost all recent forks from this repo - what users do is DISABLE nonce validation, so offering them a secure alternative and make it a choice to them to ignore it is at least miles better than having no option and people just randomly disabling nonce while there is a better option.

TBH I'm **very** disappointed that this wasn't even discussed or deeper looked into, but rather just closed, which leaves this implementation in a worse state than WITH this PR.

**Comment by davismatt** [comment]
Hopping on this thread - at the very least we need to evaluate whether we should be calling `verify_nonce!` if `nonce` isn't present in the jwt at all.

**Comment by bvogel** [comment]
@davismatt thank you for hopping on. Unfortunately @nov is very unresponsive and I think this gem is mostly dead, which is a shame. The situation that nonce checking is severely broken is ongoing for quite some time and I thought my proposed solution would be a good balance between security and feasibility, alas it was shot down without further discussion

**Comment by davismatt** [comment]
I ended up monkey patching the verify method to `verify_nonce!(id_token) if id_token[:nonce_supported] && id_token[:nonce].present?`. Apple's documentation makes it clear the nonce is an optional value and will not be present in the JWT if not included in the initial configuration. I don't know why this gem treats it like a required field.

**Comment by GastonThese** [comment]
@bvogel  Hello,

I configured nonce: :ignore, and now the "Sign in with Apple" button doesn't work. It fails to access the "users/auth/apple" route. Before I made this configuration, I could access the route and enter my username and password successfully, but it was failing at the callback.

The error I'm getting is:
E, [2023-10-26T11:23:00.952628 #297744] ERROR -- omniauth: (apple) Authentication failure! no implicit conversion of nil into Hash: TypeError, no implicit conversion of nil into Hash
:/

-------------------------------------------------------------
this monkypatch work

```
def authorize_params
  super if options[:nonce] == :ignore

  super.merge(nonce: new_nonce)
end 
```

**Comment by bvogel** [comment]
will look into this next week, sorry about that. However, I strongly suggest to not use `ignore` but prefer the new `local` option I introduced (and I know will work) which will maintain `nonce` safety

**Comment by GastonThese** [comment]
@bvogel 
In the end, it didn't work out. I was able to obtain the data from Apple, and indeed, in the callback controller, I could create the user. However, when I use sign_in_and_redirect from Devise, it doesn't work. The user isn't logged in. While debugging, I can see that the current user is created and more, but in the redirect, it says that I need to log in.

One thing I noticed is that the Google Omniauth session has different data compared to this one :/

I also tried configuring it in :local, but it didn't work.

Is there any example or tutorial on how to implement this gem? Thanks for your response :)

**Comment by bvogel** [comment]
@GastonThese if you get the data correctly from Apple and are able to create the user than the job of this gem is done. If you aren't logged in that's something that you'll have to check with the general devise/omniauth integration, as all this gem does is provide the necessary authentication and user info from Apple, how you proceed from there isn't part of this gem.

**Comment by bvogel** [comment]
@GastonThese I fixed the error in the parameter handling. See #111

**Pull request closed without merging**
